### ISSUE TITLE
optimization parsing

### ISSUE THREAD

**Issue by EvgenyKusmenko** [MontiSim/server#9]

**Comment by EvgenyKusmenko** [comment]
batch commit as alternative solution

**Comment by pbilov** [comment]
Bulk insert of nodes (for EnvObject) and tracks (for Scenario) **done**.
- writing to DB time decreased with approx. 60% (e.g. for 0.5GB file: ~70 min -> ~28min)
- reuse of DB connections (to be considered). Yet not necessary, since no user specific requests are allowed during server initialization phase.

**Comment by pbilov** [comment]
.
